spring.application.name=qm-measurement-service
server.port=8082

spring.datasource.url=jdbc:h2:mem:measurementdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=dGVzdGRHVnpkR1JsYzNSbFpHVnlkR2x1WjNOaFkzSmxkR2x2YmkxclpYaz0
app.jwt.expiration=86400000
