spring.application.name=qm-auth-service
server.port=${PORT:8081}

spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=dGVzdGRHVnpkR1JsYzNSbFpHVnlkR2x1WjNOaFkzSmxkR2x2YmkxclpYaz0
app.jwt.expiration=86400000

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
